name: CI

on:
  push:
    tags-ignore: [ '*' ]

jobs:
  run-on-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      # Seemingly something mise installs breaks post-checkout.
      # this runs a post-task after post-mise (for caching) but before post-checkout
      - name: Clean up Mise
        uses: gacts/run-and-post-run@v1
        with:
          run: echo "Nothing"
          post: mise implode -y
      - name: Install tools
        uses: jdx/mise-action@v3
      - name: Lint helm chart
        run: mise lint
      - name: Deploy and test helm chart
        run: mise test
      - name: Debug failure summaries
        if: failure()
        run: |
          echo "Helm list"
          helm list -A
          echo ""
          echo ""
          echo "kubectl get all pods"
          kubectl get pods -A -o wide
      - name: Debug describe pods
        if: failure()
        run: |
          kubectl describe pods -A
